discovery.service:
  hostname: "localhost"
  port: "8010"
  path: "eureka"

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadata-map:
      metrics:
        path: /actuator/prometheus
  client:
    serviceUrl:
      defaultZone: "http://${discovery.service.hostname}:${discovery.service.port}/${discovery.service.path}"


server:
  error:
    include-message: always
  port: 0

springdoc:
  swagger-ui:
    configUrl: '/films/v3/api-docs/swagger-config'
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: false
    url: '/films/v3/api-docs'

spring:
  application:
    name: "films"
  data:
    mongodb:
      host: "localhost"
      port: 6001
      username: "mongo"
      password: "root"
      database: "film-db"
  jackson:
    default-property-inclusion: NON_NULL

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
